# image will be published to ghcr.io/<user>/<name>
name: machinae-ublue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
      
  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://copr.fedorainfracloud.org/coprs/yohane-shiro/wallpaper-engine-kde-plugin-qt6/repo/fedora-41/yohane-shiro-wallpaper-engine-kde-plugin-qt6-fedora-41.repo
    install:
      - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      - wallpaper-engine-kde-plugin-qt6
      - bootc
      - iwd
      - tailscale
      - wireguard-tools
      - dnsmasq
      - openresolv
      - distrobox
      - steam-devices
      - android-tools
      - tmux
      - vim
    remove:
      - firefox
      - firefox-langpacks

  - type: akmods
    base: main
    install:
      - xone
      - xpadneo
      - akmod-hp-wmi-0-0.10.x86_64.rpm
      - hp-wmi-0-0.10.x86_64.rpm
      - kmod-hp-wmi-0-0.10.x86_64.rpm
      
  - type: systemd
    system:      
      enabled: 
      - dconf-update
      - hp-set-lighting
      disabled:
      - wpa_supplicant

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
      - com.bitwarden.desktop
      - net.cozic.joplin_desktop
      - org.cryptomator.Cryptomator
      - net.rpcs3.RPCS3
      - com.plexamp.Plexamp
      - tv.plex.PlexDesktop
      - tv.plex.PlexHTPC
      - com.discordapp.Discord
      - org.signal.Signal
      - com.google.AndroidStudio
      - dev.zed.Zed
      - app.devsuite.Ptyxis
      - net.davidotek.pupgui2
      - dev.lizardbyte.app.Sunshine
      - net.lutris.Lutris
      - com.github.tchx84.Flatseal
      - it.mijorus.gearlever
      - io.github.dvlv.boxbuddyrs

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
