# image will be published to ghcr.io/<user>/<name>
name: machinae-ublue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
       - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
      - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      - iwd
      - tailscale
      - wireguard-tools
      - dnsmasq
      - openresolv
      - distrobox
      - steam-devices
      - android-tools
      - ffmpeg
		  - gstreamer1-plugin-libav
		  - gstreamer1-plugins-bad-free-extras
		  - gstreamer1-plugins-bad-freeworld
		  - gstreamer1-plugins-ugly
		  - gstreamer1-vaapi
    remove:
      - fedora-workstation-repositories
      - firefox
      - firefox-langpacks
      - wpa_supplicant
      - ffmpeg-free
		  - libavcodec-free
		  - libavdevice-free
		  - libavfilter-free
		  - libavformat-free
		  - libavutil-free
		  - libpostproc-free
		  - libswresample-free
		  - libswscale-free

  - type: akmods
    base: main
    install:
      - xone
      - xpadneo
      
  - type: systemd
    system:      
      enabled: 
      - dconf-update
      disabled: 
      - wpa_supplicant

  - type: signing # this sets up the proper policy & signing files for signed images to work fully