# image will be published to ghcr.io/<user>/<name>
name: machinae-ublue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
      - source: scripts/hp-set-lighting
        destination: /usr/bin/hp-set-lighting
      - source: scripts/steam_dev.cfg
        destination: /root/steam_dev.cfg

  - type: rpm-ostree
    repos:
       - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - iwd
      - tailscale
      - wireguard-tools
      - dnsmasq
      - openresolv
      - distrobox
      - steam-devices
      - android-tools
    remove:
      - fedora-workstation-repositories
      - firefox
      - firefox-langpacks
      - wpa_supplicant

  - type: akmods
    base: main
    install:
      - xone
      - xpadneo
      
  - type: systemd
    system:      
      enabled: 
      - dconf-update
      disabled: 
      - wpa_supplicant

  - type: signing # this sets up the proper policy & signing files for signed images to work fully